### ISSUE TITLE
Update of the {import/named} ESLint rule

### ISSUE THREAD

**Issue by jancama2** [AckeeCZ/eslint-config#10]
# [import/named](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/named.md)

### What is the current rule state?

Not included

### Why have you decided to change it?

Include as an error rule

### What benefit will it bring to the rest of the team?

`Unable to resolve path to module 'rc-tooltips'`

For some reason VS Code is not complaining about non existent imports, this eslint rule does, so it would be nice to have it. 

Let's vote as follows:

- :thumbsup: for `error` value
- :handshake: to diminish to `warn`
- :thumbsdown: to turn off the rule

**Comment by horaklukas** [comment]
Is it compatible with absolute imports from `src` like `config/index`, `modules/ui`, etc. ?

**Comment by jancama2** [comment]
We use this rule normally on all project, it is just not part of the new config.

**Comment by jstorm31** [comment]
👍

**Comment by baierjak** [comment]
👍
