### ISSUE TITLE
Prettier 2.0 update

### ISSUE THREAD

**Issue by jstorm31** [AckeeCZ/eslint-config#5]
https://prettier.io/blog/2020/03/21/2.0.0.html?utm_campaign=React%2BNewsletter&utm_medium=email&utm_source=React_Newsletter_205

**Comment by cermakjiri** [comment]
neni issue spis pro prettier repo? 👀 
https://github.com/AckeeCZ/prettier-config-ackee

**Comment by jstorm31** [comment]
Aha, já myslel, že jsou spojené ta repa 😄
