### ISSUE TITLE
Update of the no-console ESLint rule

### ISSUE THREAD

**Issue by jancama2** [AckeeCZ/eslint-config#7]
# [no-console](https://eslint.org/docs/rules/no-console)

### What is the current rule state?

The rule is currently turned off

### Why have you decided to change it?

Set it to "warn".

### What benefit will it bring to the rest of the team?

It would be nice to have a feedback for forgotten console log 💣 

Let's vote as follows:

- :thumbsup: for `error` value
- :handshake: to diminish to `warn`
- :thumbsdown: to turn off the rule

**Comment by horaklukas** [comment]
🤝

**Comment by jstorm31** [comment]
🤝

**Comment by cermakjiri** [comment]
🤝 but:
- let's use `console` sparly as possible and only during development,
- and let's prefer to use middle layer for logging, for example `loglevel` package

**Comment by jstorm31** [comment]
🤝
